
version: '3.9'

services:
  custom-flask-app:
    build: .
    ports:
      - "5003:5003"
    depends_on:
      - custom-postgres-db
      - custom-mongo
    environment:
      - MONGO_URI=mongodb://custom-mongo:27017/myDatabase
      - DATABASE_URL=postgresql://username:password@custom-postgres-db:5432/myDatabase

  custom-postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: myDatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  custom-mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
